// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO-PgPQnHcKrWyET9Ojzy3362TrUF5OOM',
    appId: '1:185716976124:web:154d762c6302b005232a79',
    messagingSenderId: '185716976124',
    projectId: 'musicstreaming-9385f',
    authDomain: 'musicstreaming-9385f.firebaseapp.com',
    storageBucket: 'musicstreaming-9385f.firebasestorage.app',
    measurementId: 'G-PWW8MZXW1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkO8HkD7UNsExzn7w5pimtuWqdTraBbqo',
    appId: '1:185716976124:android:f326d2a236d9e168232a79',
    messagingSenderId: '185716976124',
    projectId: 'musicstreaming-9385f',
    storageBucket: 'musicstreaming-9385f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBULqtAs07bBEOC68yOxe6LiSwLrRyC7Fk',
    appId: '1:185716976124:ios:0fdeb10fad9df893232a79',
    messagingSenderId: '185716976124',
    projectId: 'musicstreaming-9385f',
    storageBucket: 'musicstreaming-9385f.firebasestorage.app',
    androidClientId: '185716976124-lesg131lmjp03te9ai1k0nu37pnccmqb.apps.googleusercontent.com',
    iosClientId: '185716976124-rhhhs93b6q4kk8994ndnul1jadsmvhuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttermusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBULqtAs07bBEOC68yOxe6LiSwLrRyC7Fk',
    appId: '1:185716976124:ios:0fdeb10fad9df893232a79',
    messagingSenderId: '185716976124',
    projectId: 'musicstreaming-9385f',
    storageBucket: 'musicstreaming-9385f.firebasestorage.app',
    androidClientId: '185716976124-lesg131lmjp03te9ai1k0nu37pnccmqb.apps.googleusercontent.com',
    iosClientId: '185716976124-rhhhs93b6q4kk8994ndnul1jadsmvhuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttermusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO-PgPQnHcKrWyET9Ojzy3362TrUF5OOM',
    appId: '1:185716976124:web:b0c9dcfb63fe186e232a79',
    messagingSenderId: '185716976124',
    projectId: 'musicstreaming-9385f',
    authDomain: 'musicstreaming-9385f.firebaseapp.com',
    storageBucket: 'musicstreaming-9385f.firebasestorage.app',
    measurementId: 'G-21TCTHNDJC',
  );
}
